replicaCount: 2

image:
  repository: andikapri/argocd-app-service1
  tag: "20260418-1615-2"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: staging.kube.rayhan-belajar.my.id
  tls:
    - hosts:
        - staging.kube.rayhan-belajar.my.id
      secretName: staging-kube-rayhan-belajar-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer-nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/service-upstream: 'true'

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  APP_ENV: staging
  LOG_LEVEL: info

livenessProbe:
  httpGet:
    path: /hello
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /hello
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
